config/routes.rb
Myteeroom::Application.routes.draw do

  resource :tinies

	match "/store", :to => "store#list", :as => "store"

  resources :user_sessions

  resources :users

  resources :line_items

  resources :items

  resources :carts

	get "store/list"
  get "store/index"

  resources :products

	resources :store

	get "home/index"

	match "/login" , :to => "user_sessions#new"  , :as => "login"
  match "/logout" , :to => "user_sessions#destroy" , :as => "logout"
  match "/register", :to => "users#new", :as => "register"
  match "/", :to => "store#index", :as => "root"
  match "/add_to_cart/:product_id", :to => "carts#add_to_cart", :as => "add_to_cart"
  match ':controller(/:action(/:id))'
  match 'email/list', :to => "email#list", :as => "email_list"
  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
 has_many :line_items
 #, :dependent => destroy
end

app/models/email.rb
class Email < ActiveRecord::Base
  has_many :email_references
  validates :email, :presence => true , :uniqueness => true
end

app/models/email_reference.rb
class EmailReference < ActiveRecord::Base
  belongs_to :email
  validates :email_address, :presence => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
 	belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :tiny
 has_many :email
 before_destroy :ensure_not_referenced_by_any_line_item
 validates :title, :description, :presence => true
 validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
 validates :title, :uniqueness => true

end

app/models/tiny.rb
class Tiny < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic



end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :ok }
    end
  end

  def add_to_cart
    unless params[:product_id].nil?
      unless session[:cart].nil?
        cart = session[:cart]
        cart.push(params[:product_id])
        session[:cart] = cart
      else
        cart = []
        cart.push(params[:product_id])
        session[:cart] = cart
      end
      render :text => "added"
      return
    end
    render :text => "invalid parameters passed."
  end

end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  before_filter :validate_user_logged_in , :only => :list

  def list
  end

  def new
    @email = Email.new
  end
  def add
    unless params[:email].nil?
      @email = Email.new
      @email.email = params[:email].to_s
      unless @email.save
        render :action => "new"
        return
      end
      redirect_to :action => "references" , :id => @email.id
    end
  end
  def references
    @error = ""
  end
  def addreferences
    @error = ""
    unless params[:email].nil? and params[:id].nil?
      email = Email.find_by_id(params[:id])
      unless email.nil?
        is_inputs_are_valid = false
        params[:email].to_a.each do |email_add|
          # need to do some validation on email address
          reference = EmailReference.new
          reference.email_address = email_add
          reference.email_id = email.id
          reference.save
        end
        render :text => "successfully added references, now you can continue your shopping."
        return
      else
        @error = "An error occurred, please retry the page and continue. "
      end
    end
    render :action => "references"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
	 @product_header_previews = Product.find(1,2)
	 @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
		@tinies = Tiny.find_all_by_product_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
	end
	def list
		@products = Product.all
	end


end

app/controllers/tinies_controller.rb
class TiniesController < ApplicationController

  # GET /tinies
  # GET /tinies.json
  def index
    unless params[:id].nil?
      @tinies = Tiny.find_all_by_product_id(params[:id])
      render :layout =>  false
    else
      redirect_to :controller => "products", :action =>  "index"
    end
  end

   # GET /tinies/new
  # GET /tinies/new.json
  def new
    unless params[:id].nil?
      @tiny = Tiny.new
      @tiny.product_id = params[:id]
      render :layout => false
    else
      redirect_to :controller => "products", :action =>  "index"
    end
  end

  # GET /tinies/1/edit
  def edit
    @tiny = Tiny.find(params[:id])
    render :layout => false
  end

  # POST /tinies
  # POST /tinies.json
  def create
    @tiny = Tiny.new(:small_image_url => params[:small_image_url],:large_image_url => params[:large_image_url],
										 :tinyPreview => params[:tinyPreview],
										 :product_id => params[:id])
    respond_to do |format|
      if @tiny.save
        redirect_to :controller => "products" , :action => "index"
      else
        format.html { render action: "new" }
        format.json { render json: @tiny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tinies/1
  # PUT /tinies/1.json
  def update
    @tiny = Tiny.find(params[:id])
    if @tiny.update_attributes(:small_image_url => params[:small_image_url],
															 :large_image_url => params[:large_image_url], :tinyPreview => params[:tinyPreview])
      redirect_to :controller => "products", :layout => false, notice: 'Tiny was successfully updated.'
    else
      render action: "edit"
      render json: @tiny.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tinies/1
  # DELETE /tinies/1.json
  def destroy
    @tiny = Tiny.find(params[:id])
    @tiny.destroy
    respond_to do |format|
      format.html { redirect_to tinies_url }
      format.json { head :ok }
    end
  end

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :layout => false
  end
def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registered successfully"
      redirect_to store_url
    else
      render :action => "new", :layout => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tinies_helper.rb
module TiniesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/tinies/edit.html.erb
<h1>Editing tiny</h1>

  <form action="/tinies/update">
  <% if @tiny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tiny.errors.count, "error") %> prohibited this tiny from being saved:</h2>

      <ul>
      <% @tiny.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <label>Small Image URL</label> <br />
    <input type="text" value="<%= @tiny.small_image_url %>" name="small_image_url" />
  </div>
  <div class="field">
    <label>Large Image URL</label> <br />
    <input type="text" value="<%= @tiny.large_image_url %>" name="large_image_url" />
  </div>
	<div class="field">
	 <label>Tiny Preview URL</label> <br />
	 <input type="text" value="<%= @tiny.tinyPreview %>" name="tinyPreview" />
 </div>
  <div class="field">
    <input type="hidden" value="<%= @tiny.product_id %>" name="id" />
  </div>
  <div class="actions">
    <input type="submit" value="update">
  </div>
  </form>

<%= link_to 'Back', :controller => "products", :action => "index" %>

app/views/tinies/index.html.erb
<h1>Listing tinies</h1>

<table>
  <tr>
    <th>Small image url</th>
    <th>Large image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tinies.each do |tiny| %>
  <tr>
    <td><%= tiny.small_image_url %></td>
    <td><%= tiny.large_image_url %></td>
	 	<td><%= tiny.tinyPreview %></td>
	 	<td><%= tiny.product_id %></td>
    <td><%= link_to 'Edit', "/tinies/edit/" + tiny.id.to_s %></td>
    <td><%= link_to 'Destroy', "/tinies/destroy/" + tiny.id.to_s , confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/tinies/new.html.erb
<h1>New tiny</h1>

  <form action="/tinies/create">
  <% if @tiny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tiny.errors.count, "error") %> prohibited this tiny from being saved:</h2>

      <ul>
      <% @tiny.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <label>Small Image URL</label> <br />
    <input type="text" value="<%= @tiny.small_image_url %>" name="small_image_url" />
  </div>
  <div class="field">
    <label>Large Image URL</label> <br />
    <input type="text" value="<%= @tiny.large_image_url %>" name="large_image_url" />
  </div>
	<div class="field">
    <label>Tiny Image URL</label> <br />
    <input type="text" value="<%= @tiny.tinyPreview %>" name="tinyPreview" />
  </div>
  <div class="field">
    <input type="hidden" value="<%= @tiny.product_id %>" name="id" />
  </div>
  <div class="actions">
    <input type="submit" value="Create">
  </div>
  </form>

<%= link_to 'Back', :controller => "products", :action => "index" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render 'form' %>