config/routes.rb
Myteeroom::Application.routes.draw do

  resource :tinies

	match "/store", :to => "store#list", :as => "store"

  resources :user_sessions

  resources :users

  resources :line_items

  resources :items

  resources :carts

	get "store/list"
  get "store/index"

  resources :products

	resources :store

	get "home/index"

	match "/login" , :to => "user_sessions#new"  , :as => "login"
  match "/logout" , :to => "user_sessions#destroy" , :as => "logout"
  match "/register", :to => "users#new", :as => "register"
  match "/", :to => "store#index", :as => "root"
  match "/add_to_cart/:product_id", :to => "carts#add_to_cart", :as => "add_to_cart"
  match ':controller(/:action(/:id))'
  match 'email/list', :to => "email#list", :as => "email_list"
  root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
 has_many :line_items
 #, :dependent => destroy
end

app/models/email.rb
class Email < ActiveRecord::Base
  has_many :email_references
  validates :email, :presence => true , :uniqueness => true
end

app/models/email_reference.rb
class EmailReference < ActiveRecord::Base
  belongs_to :email
  validates :email_address, :presence => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
 	belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :tiny
 has_many :email
 before_destroy :ensure_not_referenced_by_any_line_item
 validates :title, :description, :presence => true
 validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
 validates :title, :uniqueness => true

end

app/models/tiny.rb
class Tiny < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic



end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :ok }
    end
  end

  def add_to_cart
    unless params[:product_id].nil?
      unless session[:cart].nil?
        cart = session[:cart]
        cart.push(params[:product_id])
        session[:cart] = cart
      else
        cart = []
        cart.push(params[:product_id])
        session[:cart] = cart
      end
      render :text => "added"
      return
    end
    render :text => "invalid parameters passed."
  end

end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  before_filter :validate_user_logged_in , :only => :list

  def list
  end

  def new
    @email = Email.new
  end
  def add
    unless params[:email].nil?
      @email = Email.new
      @email.email = params[:email].to_s
      unless @email.save
        render :action => "new"
        return
      end
      redirect_to :action => "references" , :id => @email.id
    end
  end
  def references
    @error = ""
  end
  def addreferences
    @error = ""
    unless params[:email].nil? and params[:id].nil?
      email = Email.find_by_id(params[:id])
      unless email.nil?
        is_inputs_are_valid = false
        params[:email].to_a.each do |email_add|
          # need to do some validation on email address
          reference = EmailReference.new
          reference.email_address = email_add
          reference.email_id = email.id
          reference.save
        end
        render :text => "successfully added references, now you can continue your shopping."
        return
      else
        @error = "An error occurred, please retry the page and continue. "
      end
    end
    render :action => "references"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :validate_user_logged_in
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    render :layout => false
  end
  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    render :layout => false
  end
  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    render :layout => false
  end
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(:title => params[:product][:title], :description => params[:product][:description], :price => params[:product][:price], :image_url => params[:product][:image_url] )
    respond_to do |format|
      if @product.save
        flash[:notice] = "Product was successfully created."
        redirect_to products_url
      else
        puts @product.errors
        render :action => "new",  :layout => false
      end
    end
  end
  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit", :layout => false }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
	 @product_header_previews = Product.find(1,2)
	 @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
		@tinies = Tiny.find_all_by_product_id(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
	end
	def list
		@products = Product.all
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :layout => false
  end
def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registered successfully"
      redirect_to store_url
    else
      render :action => "new", :layout => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tinies_helper.rb
module TiniesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
	<div class="field">
    <%= f.label :smallPreview %><br />
    <%= f.text_field :smallPreview %>
  </div>
 	<div class="field">
    <%= f.label :tinyPreview %><br />
    <%= f.text_field :tinyPreview %>
  </div>
 	<div class="field">
    <%= f.label :largePreview %><br />
    <%= f.text_field :largePreview %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= truncate(strip_tags(product.description)) %></td>
    <td><%= product.price %></td>
	 	<td><%= image_tag(product.image_url) %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to "Add new tiny image", :controller => "tinies", :action => "new", :id => product.id %></td>
    <td><%= link_to "List tiny images", :controller => "tinies", :action => "index", :id => product.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/list.html.erb
<table>
    <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.price %> </td>
          <td><%= product.content_type %></td>
          <td><%= product.length %></td>
          <td><%= product.image_id %></td>
          <td><%= product.image.url %></td>
          <td><%= image_tag product.image.url %></td>
          <td><%= image_tag product.image.url(:small) %></td>
<!--      <td><img src="/image/<%= #product.id %>" alt="" ></td> -->
    </tr>
<% end %>
</table>

app/views/products/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>